name: Windows_Java_Workflow

on:
  push:
    branches: [ main ]
    
env:
  AZURE_FUNCTIONAPP_NAME: ServerlessGame-zhaw      # set this to your function app name on Azure
  POM_XML_DIRECTORY: '.'                     # set this to the directory which contains pom.xml file
  POM_FUNCTIONAPP_NAME: serverlessgame        # set this to the function app name in your local development environment
  JAVA_VERSION: '11'                      # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    # If you want to use publish profile credentials instead of Azure Service Principal
    # Please comment this 'Login via Azure CLI' block
    #- name: 'Login via Azure CLI'
    #  uses: azure/login@v1
    #  with:
    #    creds: $

    - name: Setup Java 1.8.x
      uses: actions/setup-java@v1
      with:
        # If your pom.xml <maven.compiler.source> version is not in 1.8.x
        # Please change the Java version to match the version in pom.xml <maven.compiler.source>
        java-version: '1.8.x'

    - name: 'Run mvn'
      shell: pwsh
      run: |
        # If your function app project is not located in your repository's root
        # Please change your directory for maven build in pushd
        pushd ./
        mvn clean package
        mvn azure-functions:package
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        # If your function app project is not located in your repository's root
        # Please consider prefixing the project path in this package parameter
        package: ./target/classes/org/${{ env.POM_FUNCTIONAPP_NAME }}/functions
        # If you want to use publish profile credentials instead of Azure Service Principal
        # Please uncomment the following line
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
